[package]
name = "nvcli"
version = "0.1.0"
edition = "2021"
author = "sqooid"
description = "Command line interface to change some Nvidia control panel settings"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nvapi_sys_new = {path="../nvapi"}
clap = {version="3.2.11", features=["derive"]}